### ISSUE TITLE
Who uses this GithubAction?

### ISSUE THREAD

**Issue by OskarStark** [OskarStark/phpstan-ga#1]
https://github.com/mailgun/mailgun-php/pull/530

https://github.com/phpDocumentor/FlyFinder/pull/13

**Comment by mickaelandrieu** [comment]
https://github.com/PrestaShop/circuit-breaker

Thanks, I've managed to create my own GA based on yours :+1: 

Mickaël

**Comment by OskarStark** [comment]
Great thank you for your feedback. Do you had some problems using mine?

**Comment by OskarStark** [comment]
Btw would be great if you can tweet it 🤗

**Comment by mickaelandrieu** [comment]
no issues at all with your owns but I needed others tools (phpqa from Ezdesign) and Psalm from Vimeo.

I'll tweet, and I plan to blog about it next week.

We should "group" every PHP quality GitHub actions in an Open Source organisation, wdyt?

**Comment by garak** [comment]
I'm trying to add this action, but I'm getting some errors that appear to be related to missing phpunit extension.
See https://github.com/dustin10/VichUploaderBundle/runs/1657693820

I see that action log says "Installed PHPStan extensions  No dependencies installed. Try running composer install or update." but I don't understand why :disappointed:
