### ISSUE TITLE
'check suite has disabled re-running individual checks'

### ISSUE THREAD

**Issue by staabm** [OskarStark/phpstan-ga#12]
not sure why this happens, but it seems the phpstan-ga action is not re-runnable.

dont know whether this is something you can influence on your end, but it would be usefull to re-trigger a check (e.g. because the underlying docker image is updated/changed)

![image](https://user-images.githubusercontent.com/120441/63462412-28f93700-c45b-11e9-8a09-83d7d94d09df.png)

**Comment by staabm** [comment]
This seems to be no longer the case. Thx to whoever fixed it

**Comment by OskarStark** [comment]
I think it’s done by github itself
