### ISSUE TITLE
Action takes long time to download

### ISSUE THREAD

**Issue by staabm** [OskarStark/phpstan-ga#14]
I can see download times around 50 secs

![9AC561F2-2065-48D8-878D-50753ED7631A](https://user-images.githubusercontent.com/120441/65373300-db4f3480-dc7b-11e9-9ecd-e1b2b6d4dafe.jpeg)

In comparison to the php-cs-fixer ga which takes around 6 secs this seems a lot

See https://github.com/staabm/SysMonitor/pull/12/checks?check_run_id=230924420

**Comment by staabm** [comment]
@localheinz any idea why this might be the case.

**Comment by localheinz** [comment]
@staabm 

Can’t say.

Just re-ran all checks for https://github.com/localheinz/composer-normalize-action-example/pull/2, and it took only 6 seconds, see https://github.com/localheinz/composer-normalize-action-example/pull/2/checks?check_run_id=230967336.

**Comment by localheinz** [comment]
@staabm 

Perhaps it was just a temporary anomaly? Looks like https://github.com/staabm/SysMonitor/pull/12/checks?check_run_id=230924420 was quite fast, actually.

**Comment by staabm** [comment]
Maybe the link above was misleading: https://github.com/staabm/SysMonitor/pull/12/checks?check_run_id=230924423

You need to look at the phpstan job

**Comment by localheinz** [comment]
@staabm 

Maybe it’s faster when using a tag?

**Comment by staabm** [comment]
I guess the problem is that the docker image has so much layers and those get pulled one after another.

Maybe squashing the docker image might be a option
https://github.com/jwilder/docker-squash

**Comment by OskarStark** [comment]
But never the less, they should be cached, right and it doesnt explain why its sometimes fast... 🤔

**Comment by smoench** [comment]
I'm facing the same download time https://github.com/sensiolabs-de/deptrac/pull/274/checks?check_run_id=307579185. Is there a possibility to change the docker base image (~377MB) to an alpine one as it is done in https://github.com/OskarStark/php-cs-fixer-ga?

**Comment by OskarStark** [comment]
Yes sure I just used it in the past to start quickly, but a switch to alpine should be very helpful!
Are you willing to provide a PR?

**Comment by smoench** [comment]
@staabm you might want to try the latest `0.11.19.1`-tag. It has an alpine base image now.
Originally the docker image had a size of 393.03 MB but with alpine only 44.43 MB.
