### ISSUE TITLE
[Feature Request] Comment phpstan result

### ISSUE THREAD

**Issue by core23** [OskarStark/phpstan-ga#18]
It would be nice if this action would comment the phpstan results, if there are some erorrs. If you rerun the action, it could update the created comment, like codecov does (e.g. https://github.com/core23/ShariffBundle/pull/36#issuecomment-565627606)

(Not sure if this is even possible in the current stage of the GitHub actions.)

**Comment by OskarStark** [comment]
It is possible yes (technically)

**Comment by core23** [comment]
This is working now 🚀 

Not as a comment, but GitHub has some nice integration in the changes tab.
