### ISSUE TITLE
No PHPStan extensions

### ISSUE THREAD

**Issue by garak** [OskarStark/phpstan-ga#40]
I'm trying to use this action, but I'm getting errors related to PHPUnit mocks.
It looks like the docker image is not including any extension, and I can't find a way to install one.
See https://github.com/dustin10/VichUploaderBundle/actions (the last one is a try to add an extension, but it didn't work)

**Comment by OskarStark** [comment]
Hmm the phpunit extension is already installed: https://github.com/OskarStark/phpstan-ga/blob/020c5ead88fe014388c68ecf2b438de56e674aed/Dockerfile#L24

**Comment by garak** [comment]
So, why this?
![Schermata da 2021-01-07 10-43-13](https://user-images.githubusercontent.com/179866/103877325-30af8f00-50d5-11eb-9eab-2862c126f97c.png)

My local run of phpstan (same version, with extension installed) is not showing such errors

**Comment by OskarStark** [comment]
Strange 🤔

**Comment by garak** [comment]
Maybe it depends on phpstan/extension-installer?
I see a [note](https://github.com/phpstan/extension-installer#limitations) about using or not using scripts.
We can try removing `--no-scripts` flag when running composer command in entrypoint.sh

**Comment by OskarStark** [comment]
Based on https://github.com/phpstan/extension-installer#limitations:

> The extension installer depends on Composer script events, therefore you cannot use --no-scripts flag.

You are right, lets remove it and see if it works.

cc @Nyholm for your info

**Comment by OskarStark** [comment]
Closed by #41

**Comment by OskarStark** [comment]
I tagged a release https://github.com/OskarStark/phpstan-ga/releases/tag/0.12.67.1 , can you please test it and give some feedback @garak ? Thank you

**Comment by garak** [comment]
It works now! Thank you
