### ISSUE TITLE
Tags new versions

### ISSUE THREAD

**Issue by jderusse** [OskarStark/phpstan-ga#51]
[Async AWs](https://github.com/async-aws/aws) uses this github action (thank you :heart:)

The issue is, we use fixed versions (it prevents red CI on pull requests when a new version of phpstan detects new issue in the codebase)
But the last available tag is [1.0.1](https://hub.docker.com/r/oskarstark/phpstan-ga/tags)
Is it possible to tag the docker image (and/or this repo) when you release a new version that [upgrade phpstan](https://github.com/OskarStark/phpstan-ga/commit/8059ab63bd7f15e5d66a3fa08a85495922139a33)?

**Comment by OskarStark** [comment]
You are welcome

Hmm I have an automatic dockerhub build pipeline running when tagging a release.

Will check tomorrow when back from holiday

**Comment by OskarStark** [comment]
I tagged 1.4.6, the docker image should be available shortly.

**Comment by jderusse** [comment]
Thank you :heart:
