### ISSUE TITLE
Automatically push the docker image

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [OskarStark/phpstan-ga#57]
@OskarStark what do you think about adding a step into Github actions to push automatically the docker image?
I have seen in the docker hub that you push the image every minor usually.
Instead, we can create a step that every time you create a new release of phpstan-ga automatically pushes the docker.

We are using your same strategy here: https://github.com/phparkitect/arkitect-github-actions
But I have to remember every time to push the docker manually.

What do you think?

**Comment by OskarStark** [comment]
If I create a release a build is triggered on dockerhub, but I would prefer to do it on the Github side 👍

**Comment by OskarStark** [comment]
I would love to have the same for https://github.com/OskarStark/php-cs-fixer-ga and https://github.com/OskarStark/doctor-rst

**Comment by OskarStark** [comment]
This is done
