### ISSUE TITLE
Deprecation error message when using "uses: docker://oskarstark/phpstan-ga"

### ISSUE THREAD

**Issue by kenguest** [OskarStark/phpstan-ga#65]
Using this via "uses: docker://oskarstark/phpstan-ga", I get this error message

The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by OskarStark** [comment]
This looks like it is about actions/checkout action. Try to use v3 there please
